name: Clickyleaks Full Scanner

on:
  schedule:
    - cron: '0 */4 * * *'  # ⏰ Every 4 hours
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DOMAINR_API_KEY: ${{ secrets.DOMAINR_API_KEY }}
      GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
      GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libxss1 libasound2t64 libxshmfence1 libxrandr2 libgbm1 \
            libgtk-3-0 xvfb unzip jq wget

      - name: Install latest compatible Chrome
        run: |
          CHROME_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json \
            | jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64") | .url')
          wget "$CHROME_URL" -O chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome
          google-chrome --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install undetected-chromedriver selenium

      - name: Run Clickyleaks Full Scanner
        run: xvfb-run python clickyleaks_full_scanner.py