name: Run YouTube8M Clickyleaks Scanner

on:
  schedule:
    - cron: "0 7,13,21 * * *"  # Runs 3x daily at 7AM, 1PM, 9PM UTC
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps

      - name: Run Clickyleaks YouTube8M Scanner
        run: python clickyleaks_full_scanner.py
