name: Clickyleaks Dynamic Explorer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"  # Run every 8 hours, adjust as needed

jobs:
  dynamic-explorer:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install playwright supabase requests
          playwright install chromium

      - name: Run Clickyleaks Dynamic Explorer
        run: python clickyleaks_dynamic_explorer.py
