name: Fetch YouTube8M Shard

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  fetch-ids:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install supabase requests
      - run: python clickyleaks_fetch_youtube8m_shard.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
