name: Clickyleaks Kaggle Scanner

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests supabase dnspython python-dotenv

      - name: Run Kaggle-based scanner
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          KAGGLE_JSON_URL: https://www.dropbox.com/scl/fi/aee4kd8lzhthegzq4d3gm/videos.json?rlkey=t6amw5ewndt3n0hm7neywhdee&dl=1
        run: |
          echo "🔁 Running Clickyleaks Kaggle JSON Scanner..."
          python clickyleaks_kaggle_scanner.py
