name: Kaggle API Test

on:
  workflow_dispatch:

jobs:
  test-kaggle-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install kaggle

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${KAGGLE_JSON}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      - name: Run Kaggle test
        run: |
          python kaggle_test.py
