name: Monitor Registered Domains

on:
  schedule:
    - cron: '*/45 * * * *'  # Every 45 minutes
  workflow_dispatch:

jobs:
  monitor-domains:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      APILAYER_KEY: ${{ secrets.APILAYER_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install supabase requests python-dotenv

      - name: Run domain monitor
        run: python monitor_registered.py
