name: Reddit Scraper (Hourly)

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-reddit-scraper:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv supabase

      - name: Run Reddit Scraper
        run: python reddit_scraper.py