name: Run Clickyleaks Trending Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9AM UTC

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install kaggle pandas

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Run Clickyleaks Trending Scanner
      run: python clickyleaks_trending_scanner.py
